### ISSUE TITLE
Odoo Server Error

### ISSUE THREAD

**Issue by gurdianimda** [hit-pay/odoo-extension#3]
Hi, there is a problem when trying to install on Odoo V16:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 599, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4397, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4308, in _load_records_create
    return self.create(values)
  File "<decorator-gen-189>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/payment/models/payment_provider.py", line 325, in create
    providers = super().create(values_list)
  File "<decorator-gen-65>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 670, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3920, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'image' on model 'payment.provider'

**Comment by committedpro** [comment]
Installed on Odoo community or enterprise?

**Comment by gurdianimda** [comment]
Community

**Comment by committedpro** [comment]
Thank you.
Let us try to reproduce this and revert back to you.

**Comment by gurdianimda** [comment]
Thanks, looking forward

**Comment by gurdianimda** [comment]
> Thanks, looking forward

Hi, any updates?

**Comment by committedpro** [comment]
Hi, it works in my server odoo 16 community.

Anyway, could you please try this?

payment_hitpay\data\payment_provider_data.xml

Remove this line <field name="image" type="base64" file="payment_hitpay/static/description/logo.png" />

And restart the odoo server and upgrade the module in developer mode.

Let me know anything else.

Thank you

**Comment by gurdianimda** [comment]
Hi, I can't edit the code. My Odoo deployment for third party apps pulls through the github repo directlly. Could you please create  it and make it available via the repo?

**Comment by committedpro** [comment]
Sorry for the late reply, I was busy with another work.
I will send you the new git repo tomorrow.

**Comment by gurdianimda** [comment]
Please do. Thank you .

**Comment by committedpro** [comment]
Hi I uploaded the updated package here: https://github.com/committedpro/odoo-extension.git

Please pull and test it and let us know.

**Comment by gurdianimda** [comment]
thanks for your kind assistance. the repo you shared with that specific edit allowed for the installation and the payment is working during our testing. thank you again. will close the issue.
